Import proposed actions to utterance table
ServiceNow/azimuth pull request #465
Opened 2023-02-24 16:24 UTC by nandhinibsn

Resolve #

## Description:

## Checklist:

You should check all boxes before the PR is ready. If a box does not apply, check it to acknowledge it.

* [ ] **ISSUE NUMBER.** You linked the issue number (Ex: Resolve #XXX).
* [ ] **PRE-COMMIT.** You ran pre-commit on all commits, or else, you
  ran `pre-commit run --all-files` at the end.
* [ ] **USER CHANGES.** The changes are added to CHANGELOG.md and the documentation, if they impact
  our users.
* [ ] **DEV CHANGES.**
    * Update the documentation if this PR changes how to develop/launch on the app.
    * Update the `README` files and our wiki for any big design decisions, if relevant.
    * Add unit tests, docstrings, typing and comments for complex sections.

2023-02-27 15:40 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    text.replace(/[^a-zA-Z0-9_]/g, "");
Can you explain why we have to remove special characters? How about if the persistent ids do contain special characters? I think it will fail.
For your information, this regular expression seems to be equivalent to this shortcut:
```suggestion
    text.replace(/\W/g, "");
```

2023-02-27 15:43 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +  row_idx: "persistentId",
It's not necessarily `row_idx`. The `persistent_id` in the config is the name of a column in the dataset containing an id that would persist throughout dataset versions. It defaults to `"row_idx"`, but the user can specify anything, for example `"incident_number"`.

2023-02-27 15:50 UTC, JosephMarinier reviewed
I don't think you need any `slice()` for that. Here are some suggestions...

2023-02-27 15:50 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          if (row) {
...and thanks to the `.trim()` I am suggesting, there shouldn't be an empty row anymore.
```suggestion
```

2023-02-27 15:59 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          }
Thanks to the `.trim()` I am suggesting, there shouldn't be an empty row anymore, so no need for this `if`.
Also, I think parsing the row can be simplified to something like this:
```suggestion
            const [persistentId, dataAction] = row.split(",");
            return { persistentId, dataAction };
```

2023-02-27 16:01 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +      Object.keys(parsedData[0]).length > 0 && updateProposedAction(parsedData);
Maybe we should toast an error if there are no rows in the CSV? Instead of ignoring silently. What do you think?

2023-02-27 20:10 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    fileReader.readAsText(file, "UTF8");
UTF-8 is the default, so we can clean that up:
```suggestion
    fileReader.readAsText(file);
```

2023-02-27 20:28 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +      <Modal open={modal} onClose={() => showModal(false)}>
The visual is not really polished.
![image](https://user-images.githubusercontent.com/8386369/221678104-5d6adcdc-f4c4-42a8-b3b3-5f01ff009844.png)
I see in MUI documentation:
> If you are creating a modal dialog, you probably want to use the [Dialog](https://mui.com/material-ui/react-dialog/) component rather than directly using Modal. Modal is a lower-level construct [...]

I think that would solve most problems you were trying to solve with `classes.modal`, and more.

2023-02-27 20:38 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
Where did you take that? I don't think we want to accept Excel sheets or anything other than `.csv`. The export comes from Azimuth and we know it has a `.csv` extension.
```suggestion
              accept=".csv"
```

2023-02-27 20:45 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    const fileReader = new FileReader();
I notice that if you import a CSV, then click the `Import` button a second time but then `Cancel`, we get this error:
```error
UtterancesTable.tsx:498 Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at importProposedActions (UtterancesTable.tsx:498:1)
    at onChange (UtterancesTable.tsx:552:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
```

2023-02-28 04:20 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        if (rows.join()) {
Any reason for joining back the array into a string? Or can you simply check the length of the array?
```suggestion
        if (rows.length) {
```

2023-02-28 04:23 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              headers.includes(h)
In the `map()` below, we assume the columns are in the right order, so I think this should check it.

2023-02-28 04:24 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              const [persistentId, dataAction] = row.trim().split(",");
Do you have an example why we need to `.trim()` here? I would not have expected that.

2023-02-28 04:36 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              "The CSV file did not have the row_idx and proposed_action column headers to update the proposed action."
Again, we are not necessarily expecting `row_idx`.

2023-02-28 04:40 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          } else {
Instead of nesting all those `if`/`else`, could you please check the different conditions for error in a linear fashion and return early of there is an error? That is much easier to read and takes up a lot less indentation.

2023-02-28 10:37 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +            className={classes.exportButton}
Not that you added `justifyContent: "space-between"` to the parent, this class is no longer useful. You can remove its definition and the two places it's used.

2023-02-28 10:41 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +            const utterancePatch: UtterancePatch[] = rows.map((row) => {
With the ` as UtterancePatch` bellow, this one is redundant:
```suggestion
            const utterancePatch = rows.map((row) => {
```

2023-02-28 10:47 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          showDialog(true);
Now that I see where the `Dialog` box is used, it seems to only be showing error messages. Right? Have you considered using `raiseErrorToast` instead? It seems more aligned with the rest of the app.
```suggestion
          raiseErrorToast("There are no records in the CSV file");
```

2023-02-28 10:59 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        const [header, ...rows] = result.split("\n");
You forgot the `.trim()` from my suggestion [here](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1118934022). Anyway, I have a more rigorous solution that gives the same result: `.slice(0, -1)`. Otherwise, there is an empty line at the end of `rows`, resulting in an error when parsing that line.
```suggestion
        const [header, ...rows] = result.split("\n").slice(0, -1);
```

2023-02-28 11:00 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        if (rows.join()) {
I guess the reason is the error I mentioned [here](https://github.com/ServiceNow/azimuth/pull/465/files#r1119895819). If you fix it there, you will be able to apply my suggestion here.

2023-02-28 14:50 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    const headers: string[] = data.slice(0, data.indexOf("\n")).split(",");
I can explain why did I ignore "trim() before doing the split. It did remove extra space but it did not remove other escape characters.

For eg: The csv records contain \r characters. So, I added trim individually to headers and rows like below:
const headers: string[] = header.trim().split(",");
const [persistentId, dataAction] = row.trim().split(",");

2023-02-28 14:50 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        if (rows.join()) {
The reason I had to join was that it created an empty string array after the split. So rows.length is calculated as 1, making the if condition true. So I had to join().

2023-02-28 14:52 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        const [header, ...rows] = result.split("\n");
Yes, true. slice would solve the problem here. I will add the suggestion. Thank you for suggesting it :)

2023-02-28 15:03 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              const [persistentId, dataAction] = row.trim().split(",");
Sure, I can give you an example: After doing split individually each row, there are still escape characters. So, trim() helped here to remove those.

<img width="1757" alt="image" src="https://user-images.githubusercontent.com/103529971/221892897-e37ff814-58f3-4a15-b711-226f9193cae0.png">

2023-02-28 15:12 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          showDialog(true);
So, do you suggest we use the "raiseErrorToast" for both scenarios?

2023-02-28 17:45 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          showDialog(true);
That's what I am contemplating, yes. What do you think?

2023-02-28 17:47 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              const [persistentId, dataAction] = row.trim().split(",");
Can you give me an example of an "escape character"? I don't see any.

2023-02-28 17:48 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        if (rows.join()) {
Yes, I understood. 👍

2023-02-28 17:58 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    const headers: string[] = data.slice(0, data.indexOf("\n")).split(",");
There doesn't seem to be `\r`s in the CSV files we generate, just `\n`s. For example, I see:
```js
{result: 'row_idx,proposed_action\n4,augment_with_similar\n5,relabel\n'}
```
Maybe there are `\r`s if the Azimuth back end runs on Windows? 🤷‍♂️ To support that, I would suggest dealing with it (optionally) when we split the lines, using a regular expression:
```diff
-        const [header, ...rows] = result.split("\n").slice(0, -1);
+        const [header, ...rows] = result.split(/\r?\n/).slice(0, -1);
```
With that, there shouldn't be the need for `trim()`ing every row.

2023-02-28 18:19 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    const headers: string[] = data.slice(0, data.indexOf("\n")).split(",");
Yeah, it works with this regex. thank you :)

2023-02-28 18:20 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    const headers: string[] = data.slice(0, data.indexOf("\n")).split(",");
I am unsure why there is a \r, but mine is on mac.

2023-02-28 18:29 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              const [persistentId, dataAction] = row.trim().split(",");
Sorry. its carriage return character (\r) I meant to denote here.

2023-02-28 18:33 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +            className={classes.exportButton}
Do you mean to say "exportButton" is not needed anymore.?

2023-02-28 18:35 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          showDialog(true);
Yes, you are right; showing an error message is an excellent idea using toast.

2023-02-28 18:42 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +            className={classes.exportButton}
Yes, this class `classes.exportButton` is no longer useful.

2023-03-01 20:47 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          } else {
Have you tested your recent changes?
Don't forget the early returns in case of errors, otherwise the execution continues and it will call `updateProposedAction()` with garbage data.

2023-03-03 23:07 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          } else {
True, It did not trigger the API call as it was empty array but the code was executed. I fixed that in my recent commit. Please check.

2023-03-03 23:08 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +      updateDataAction({
I was able to fix the issue I have been facing and changes are pushed. Now, the API should accept UtterancePatch[] .

2023-03-06 14:55 UTC, JosephMarinier requested changes
With the two following suggestions, I think you should be able to simply this bit:
```diff
-      queryFn: async ({ utterancePatch, utteranceQuery }) =>
-        responseToData(
+      queryFn: responseToData(
          fetchApi({
            path: "/dataset_splits/{dataset_split_name}/utterances",
            method: "patch",
          }),
          "Something went wrong updating proposed actions"
-        )({ ...utteranceQuery, body: utterancePatch }),
+        ),
```

2023-03-06 14:55 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +      }
I think it was perfect with ` & GetUtterancesQueryState`, instead of nesting it, so it's uniform with the other endpoints.
```suggestion
      } & GetUtterancesQueryState
```

2023-03-06 14:55 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +        }[];
That seems redundant, instead:
```suggestion
        utterancePatch: UtterancePatch[];
```
Also, I think that should be called `body` directly:
```suggestion
        body: UtterancePatch[];
```

2023-03-06 15:13 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +            }
This optimistic update doesn't work. Can you fix it and try it to make sure it works?
The `draft` is of type
```ts
    {
      utterances: Utterance[];
      utteranceCount: number;
      confidenceThreshold: number | null;
    }
```
while `utterancePatch` is of type
```ts
    UtterancePatch[]
```
so `Object.assign(draft, utterancePatch);` produces garbage.
I think the previous code, with the `forEach()`, is closer to what we need.

2023-03-06 15:19 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              headers.includes(h)
Any progress on this?

2023-03-06 16:26 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              headers.includes(h)
Hey Joseph, I started working on this today morning. I derive a solution to it and work towards it. I will be able to push it in sometime

2023-03-06 19:29 UTC, nandhinibsn commented on webapp/src/services/api.ts
> +            }
Ohh right! Thank you for pointing out to me that. Please check my recent commit and let me know if that looks ok.

2023-03-06 19:35 UTC, nandhinibsn commented on webapp/src/services/api.ts
> +        }[];
I considered the above and simplified my recent commit as much as possible. But, I face some errors I am unsure of when I remove the async with"queryFn" and call the utterancePatch as body directly. But isn't the term "utterancePatch" more readable than calling body? Or I am unsure if there is any specific reason to call it that way.

2023-03-06 19:37 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +              headers.includes(h)
Please check my latest commit and let me know what do you think of that approach.

2023-03-06 19:43 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +        }[];
This is the "request body" as seen in the generated types.
```ts
    requestBody: {
      content: {
        "application/json": components["schemas"]["UtterancePatch"][];
      };
    };
```
I called it `body` in our helper `fetchApi` to align with the native `fetch()` API, which expects `body`.
I don't pretend it is a better name, just that it allows for that code simplification.
This mutation is similar to the config mutation that has a `body`: `updateConfig({ jobId, body: partialConfig })}`.

2023-03-06 19:44 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        ) {
This makes no sense. I guess you meant `&&` instead of `||`, otherwise this will still pass if the headers are out of order, which is the problem I raised [here](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1119560156). In that case, I think `headers.includes(h)` is useless.
Why not simplify to this?
```suggestion
        if (headers !== `${config.columns.persistent_id},proposed_action`) {
```

2023-03-06 19:49 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +            `The CSV file either did not have the ${config.columns.persistent_id} and proposed_action column headers, or the columns are not in the correct order to update the proposed action.`
I think it would more straightforward to state what we expect, instead of what might be wrong. Here is a suggestion:
```suggestion
            `The CSV file must have column headers ${config.columns.persistent_id} and proposed_action, in that order.`
```

2023-03-06 20:05 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +              );
Follow up on [this](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1126572158).
That still doesn't work; `utterance` is a single utterance, while `utterancePatch.filter()` returns an array of utterances. The result of `Object.assign()` will be garbage: a combination of the original utterance and the added field `"0": <the whole utterancePatch>`.
I would suggest avoiding using `Object.assign()` as it is not strongly typed and lets you do mistakes like that.
And again, can you fix the optimistic update and **try it** to make sure it works before you commit/push? Ask questions if you need help.

2023-03-06 20:22 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +        }[];
Ah-ha! I think I know what issue you faced. The type `GetUtterancesQueryState` has a `body: never` field, so when renaming this to `body`, in combination with the other suggestion, you will have to change
```diff
-      } & GetUtterancesQueryState
+      } Omit<GetUtterancesQueryState, "body">
```

2023-03-06 20:53 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +      queryFn: async ({ utterancePatch, ...utteranceQuery }) =>
Most of the fields from `utteranceQuery` are not allowed for the `PATCH`. They are used in the `args` for `api.util.updateQueryData("getUtterances", args, ...` to perform the right optimistic update.
This should be reverted to using only `jobId` and `datasetSplitName`, as well as `utterancePatch`/`body`, and ignore the rest.
```suggestion
      queryFn: async ({ jobId, datasetSplitName, body }) =>
```

2023-03-06 20:53 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +        )({ ...utteranceQuery, body: utterancePatch }),
Accordingly:
```suggestion
        )({ jobId, datasetSplitName, body }),
```

2023-03-07 02:56 UTC, nandhinibsn commented on webapp/src/services/api.ts
> +        }[];
Okay, Thank you for explaining to me why we use the term "body". It makes sense to my confusion now. 

Exactly, that was the error message I have been facing since last week. Thank you for the suggestion to solve the issue here.

2023-03-07 02:57 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        ) {
Ohh yeah, this approach is so simple. I couldn't think of it this way earlier. thank you :)

2023-03-07 14:58 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +              return {
Follow up on [this](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1126572158) and [this](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1126975146).
That still doesn't work.
A `return` inside a `forEach` doesn't do anything. Anyway, as you can see in the documentation of [`updateQueryData()`](https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#updatequerydata:~:text=The%20callback%20receives%20an%20Immer%2Dwrapped%20draft%20of%20the%20current%20state%2C%20and%20may%20modify%20the%20draft%20to%20match%20the%20expected%20results%20after%20the%20mutation%20completes%20successfully.), we have to
> modify the `draft`

not return a new object. That's why we were assigning to `utterance.dataAction = newValue;`.

For the third time, can you try your solution to make sure it works before you commit/push? You should see the value in the dropdown menu change instantly, instead of waiting for the response from the back end. Ask questions if you need help.

2023-03-07 15:00 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +                )[0],
This `.filter(...)[0]` gives the same result as (but in a less efficient way than) `.find(...)`.
```suggestion
                ...body.find(
                  ({ persistentId }) => persistentId === utterance.persistentId
                ),
```

2023-03-07 20:32 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +                utterance.dataAction = patchUtterance.dataAction;
The name `patchUtterance` sounds like a verb and hints at a function. The name `utterancePatch`, matching the type of `body` would have been better. However, I think `found = body.find(...)` sounds even better, especially with `if (found)`. Do you like that?
```suggestion
              const found = body.find(
                ({ persistentId }) => persistentId === utterance.persistentId
              );
              if (found) {
                utterance.dataAction = found.dataAction;
```

2023-03-07 20:36 UTC, JosephMarinier commented on webapp/src/components/Utterance/UtteranceDataAction.tsx
> +      body: utterancePatch,
I find it confusing that `utterancePatch` is in fact an array of `utterancePatch`es, plural. I think in this case I would simply call it body to avoid renaming it here.
```suggestion
      body,
```

2023-03-07 20:36 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          body: utterancePatch,
Same here
```suggestion
        const body = rows.map((row) => {
          const [persistentId, dataAction] = row.split(",");
          return { persistentId, dataAction } as UtterancePatch;
        });
        updateDataAction({
          body,
```

2023-03-07 20:40 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +          return null;
`fileReader.onload` is not supposed to return anything, so I would remove those `null`s.
```suggestion
          return;
        }
        if (header !== `${config.columns.persistent_id},proposed_action`) {
          raiseErrorToast(
            `The CSV file must have column headers ${config.columns.persistent_id} and proposed_action, in that order.`
          );
          return;
```

2023-03-07 20:48 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        const [header, ...rows] = result.split(/\r?\n/).slice(0, -1);
I'm sorry for changing my mind again, but the more I think about it, the more I like my original suggestion of trimming the whole `result` before splitting. The current approach of discarding the last row with `.slice(0, -1)` would silently lose a row if there were no newline at the end of the file, which might happen if the user manually edits the file, and would result in losing data silently. I'd use `.trimEnd()` as I don't expect extra newlines at the beginning of the file, only at the end. Does that make sense?
```suggestion
        const [header, ...rows] = result.trimEnd().split(/\r?\n/);
```

2023-03-07 21:05 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +                ({ persistentId }) => persistentId === utterance.persistentId
Follow up on [this](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1126572158), [this](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1126975146) and [this](https://github.com/ServiceNow/azimuth/pull/465#discussion_r1128000847).
There is still an issue. Have you tried it with a CSV file to make sure it works?
The `utterance.persistentId` can be a `string` or a `number`. However, when reading the CSV file, there is no distinction between a `string` and a `number`, so we assume `persistentId` is a string. The back end supports that, no problem. Here, we just have to check equality with `==` instead of `===` to support that.
```suggestion
                // Support number | string
                // eslint-disable-next-line eqeqeq
                ({ persistentId }) => persistentId == utterance.persistentId
```

2023-03-07 21:40 UTC, nandhinibsn commented on webapp/src/services/api.ts
> +                ({ persistentId }) => persistentId === utterance.persistentId
Yes, it did work for me with the sample import of data. It's good to use equality to avoid the type-checking, but I wonder why the type would be changed in the CSV

2023-03-07 21:44 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +                ({ persistentId }) => persistentId === utterance.persistentId
There is no typing in CSV. There is no way to tell if `...,42,...` is the number `42` or the string `"42"`. Does that make sense?

2023-03-07 21:50 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +        const [header, ...rows] = result.split(/\r?\n/).slice(0, -1);
Otherwise, we should check if there is any new line at the end to do a slice(0,-1).

2023-03-07 21:51 UTC, nandhinibsn commented on webapp/src/services/api.ts
> +                utterance.dataAction = patchUtterance.dataAction;
Sounds good to me. how about foundPersistenId or foundId?

2023-03-07 21:52 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +                utterance.dataAction = patchUtterance.dataAction;
It would be a `foundUtterancePatch`, but I don't think this extra information is necessary, given the scope of this variable is so small.

2023-03-07 22:48 UTC, nandhinibsn commented on webapp/src/services/api.ts
> +                ({ persistentId }) => persistentId === utterance.persistentId
Yes :)

2023-03-08 00:36 UTC, JosephMarinier commented on webapp/src/services/api.ts
> +                ({ persistentId }) => persistentId === utterance.persistentId
Please add the comments I suggested, otherwise we get a warning in the terminal.

2023-03-08 18:11 UTC, JosephMarinier commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    fileReader.onload = ({ target }) => {
Bug: When importing a CSV file of proposed actions, importing the same file path twice fails silently. The file browser closes normally but the `fileReader.onload` is never called.
Use case: One might have edited the file and wants to re-import it.
Workaround: Refresh the app.
Let's fix that in another PR. I filed a bug: #479

2023-03-08 18:14 UTC, JosephMarinier approved these changes
Very cool feature! 👍

2023-03-08 19:04 UTC, nandhinibsn commented on webapp/src/components/Analysis/UtterancesTable.tsx
> +    fileReader.onload = ({ target }) => {
Ohh, Let me check that use case. Thanks for finding that out and creating a follow-up issue for it.

2023-03-08 19:04 UTC, nandhinibsn commented
> Very cool feature! 👍

I appreciate your patience in reviewing it and your input. :) Thank you.

2023-03-08 19:05 UTC, merged